@startuml
'https://plantuml.com/class-diagram

interface NmmObjectBaseInterface{
}
abstract class NmmObjectBase{
}
abstract class Part{
}
class FilePath
class DataStructure

Object <|.. ObjectInterface
Part <|-- Object
FilePath <|-- Part
DataStructure <|-- Part

interface PropertyInterface{
}
abstract class Property{
}
class Path

Property <|.. PropertyInterface
Path <|-- Property
FilePath o-- Path

abstract class Model{
}

class PreprocessModel{
}

Model <|-- Object
PreprocessModel <|- Model
PreprocessModel o-- FilePath
PreprocessModel o-- DataStructure

@enduml